version: "3.11"
services:
  db:
    image: postgres:15.4
    container_name: postgres_container
    command: -p 6000
    expose:
      - 6000
    env_file:
      - .env

  app:
    build:
      context: .
    env_file:
      - .env
    container_name: fastapi_app
    command: ["/fastapi_app/docker/app.sh"]
    ports:
      - 6002:8000
    depends_on:
      - db