"""Test

Revision ID: 5456ef892b0c
Revises: 
Create Date: 2023-12-22 12:49:53.340809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5456ef892b0c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('header', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user_table.id'], use_alter=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['user_table.id'], use_alter=True),
    sa.ForeignKeyConstraint(['updated_by'], ['user_table.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('body'),
    sa.UniqueConstraint('header')
    )
    op.create_table('role_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user_table.id'], use_alter=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['user_table.id'], use_alter=True),
    sa.ForeignKeyConstraint(['updated_by'], ['user_table.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user_table.id'], use_alter=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['user_table.id'], use_alter=True),
    sa.ForeignKeyConstraint(['role_id'], ['role_table.id'], use_alter=True),
    sa.ForeignKeyConstraint(['updated_by'], ['user_table.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user_table.id'], use_alter=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['user_table.id'], use_alter=True),
    sa.ForeignKeyConstraint(['post_id'], ['post_table.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user_table.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_history_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('previous_header', sa.String(), nullable=False),
    sa.Column('previous_body', sa.String(), nullable=False),
    sa.Column('new_header', sa.String(), nullable=False),
    sa.Column('new_body', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['new_body'], ['post_table.body'], ),
    sa.ForeignKeyConstraint(['new_header'], ['post_table.header'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post_table.id'], ),
    sa.ForeignKeyConstraint(['previous_body'], ['post_table.body'], ),
    sa.ForeignKeyConstraint(['previous_header'], ['post_table.header'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment_history_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('previous_body', sa.String(), nullable=False),
    sa.Column('new_body', sa.String(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comment_table.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment_history_table')
    op.drop_table('post_history_table')
    op.drop_table('comment_table')
    op.drop_table('user_table')
    op.drop_table('role_table')
    op.drop_table('post_table')
    # ### end Alembic commands ###
