"""empty message

Revision ID: 59480fa97303
Revises: 64d5b1819df8
Create Date: 2023-09-07 12:40:38.167765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59480fa97303'
down_revision: Union[str, None] = '64d5b1819df8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'user_table', 'role_table', ['role_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_table', type_='foreignkey')
    # ### end Alembic commands ###
