"""Altered tables 2

Revision ID: 7c84318156f4
Revises: e1971f990e9b
Create Date: 2023-09-21 11:32:59.985838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c84318156f4'
down_revision: Union[str, None] = 'e1971f990e9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operation_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.String(), nullable=False),
    sa.Column('figi', sa.String(), nullable=False),
    sa.Column('instrument_type', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user_table.id'], use_alter=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['user_table.id'], use_alter=True),
    sa.ForeignKeyConstraint(['updated_by'], ['user_table.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'user_table', 'role_table', ['role_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_table', type_='foreignkey')
    op.drop_table('operation_table')
    # ### end Alembic commands ###
